### PR TITLE
fix: Updated and simplified install instructions

### PR DESCRIPTION
**Pull request by aryanprince**
✅ Outdated instructions have now been updated for the latest version of Windows Terminal
✅ Simplified the instructions 
✅ Added **bold text** for selectable options for readability
✅ Added a couple of keyboard shortcuts
✅ Also added myself to the 'Thanks' section

### CODE REVIEW

**Comment by aryanprince** [comment]
@nekowinston Apologize for the ping, any thoughts/updates on the PR?

**Comment by nekowinston** [comment]
> @nekowinston Apologize for the ping, any thoughts/updates on the PR?

No worries, thanks for the reminder. Looks good, a small improvement might be to use the `<kbd></kbd>` tags for shortcuts like <kbd>Ctrl + ,</kbd>.

Can't test the instructions myself since I don't use Windows, but I'll merge it once those changes are made.

**Comment by aryanprince** [comment]
@nekowinston Ty for the suggestion, added them in. Looks good now?

**Comment by nekowinston** [comment]
Thanks!

**Pull request merged**
