### PR TITLE
Remove accented e for alignment with frappeTheme.json

### PR DESCRIPTION
**Pull request by adamjames**
Wasn't sure whether to add it in here or remove it - I went with remove since none of the other files use accented letters.

Fixes Powershell falling back to the default when trying to use Frappe.

### CODE REVIEW

**Comment by justTOBBI** [comment]
Can't replicate the issue in the first place. Works on my machine xd

**Comment by adamjames** [comment]
How odd! Let me reconfirm, I could have made a mistake :)

**Comment by justTOBBI** [comment]
Sorry, issue on my side. I forgot that I changed the name of my theme. If it's broken for you, its most likely broken for everyone.

**Comment by adamjames** [comment]
Fair enough then :) I double-checked this once more and I'm happy that it's just the accented e that needed adjusting. Are we okay to merge?

**Pull request merged**
